### ISSUE TITLE
Оцифровка/Распознавание распечаток исходников (для тестирования)

### ISSUE THREAD

**Issue by mrkeuz** [askfind/Emulator-Setun-1958#4]
### Предложение:

За счет того, что в исходниках сетуни содержатся чек. суммы. 
Можно гарантированно распознавать (OCR) исходные коды программ их архивов и документов.

### Плюсы

- Будет большой объем оцифрованных исходников для тестов эмулятора Сетуни

### Возможные проблемы

- Шрифты печатных машинок. Именно русские.
  Не знаю, на сколько они заточены под печатный текст тех годов, поэтому потребуется человек для настройки таких продуктов как [Tesseract](https://ru.wikipedia.org/wiki/Tesseract). Может быть придется "тренировать" свой шрифт. Сам о распознавании знаю только что семи-сегментные экраны сложно распознавать - глифы букв разделены промежутком и просто так шрифт такой не отсканировать. Возможно я преувеличиваю проблему ) И уже давно есть решение

@askfind, предлагаю поставить "label" для задачи "Help wanted". Для поиска добровольцев, специалистов в этой теме

**Comment by askfind** [comment]
Исходные коды, распечатанные в книгах, вводятся вручную.
